image: gradle:jdk17

stages:
  - build
  - test
  - jacoco
  - deploy

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

jacoco:
  stage: jacoco
  script: gradle jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html
    expire_in: 1 week

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production